# Generated by Django 5.2.1 on 2025-09-11 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('reason', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('medical', 'Медицинское лечение'), ('charity', 'Благотворительность'), ('other', 'Другое')], max_length=50, verbose_name='Повод')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма сбора')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма на данный момент')),
                ('donors_count', models.PositiveIntegerField(default=0, verbose_name='Количество доноров')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Обожка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сбор',
                'verbose_name_plural': 'Сборы',
                'ordering': ('-created_at',),
            },
        ),
    ]
