# Generated by Django 5.2.1 on 2025-09-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='reason',
            field=models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('medical', 'Медицинское лечение'), ('charity', 'Благотворительность'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Повод'),
        ),
    ]
